package style

import (
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

func writeTree(t *testing.T, files map[string]string) string {
	t.Helper()
	root := t.TempDir()
	for name, body := range files {
		path := filepath.Join(root, filepath.FromSlash(name))
		if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(path, []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
	}
	return root
}

func TestTreeExclusions(t *testing.T) {
	bad := "package p\n\nfunc Bad() {}\n"
	root := writeTree(t, map[string]string{
		"go.mod":                  "module example.com/p\n",
		"ok.go":                   "package p\n",
		"sub/bad.go":              bad,
		"vendor/x/bad.go":         bad,
		"testdata/bad.go":         bad,
		".hidden/bad.go":          bad,
		"_scratch/bad.go":         bad,
		"nested/go.mod":           "module example.com/nested\n",
		"nested/bad.go":           bad,
		"notes.txt":               "// not go",
		"sub/deeper/generated.go": "// Code generated by hand. DO NOT EDIT.\n\npackage deeper\n\nfunc Bad() {}\n",
	})
	findings, err := AnalyzeTree(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(findings) != 1 || findings[0].File != "sub/bad.go" {
		t.Fatalf("findings = %+v", findings)
	}
}

func TestTreeReportsFailuresSeparately(t *testing.T) {
	root := writeTree(t, map[string]string{
		"a.go":   "package p\n\nfunc {\n",
		"b.go":   "package p\n\nfunc B() {}\n",
		"c/c.go": "package c\n",
	})
	findings, err := AnalyzeTree(root)
	if err == nil {
		t.Fatal("parse failure not reported")
	}
	if len(findings) != 1 || findings[0].File != "b.go" {
		t.Fatalf("findings = %+v", findings)
	}
}

func TestTreeUnreadableFile(t *testing.T) {
	if runtime.GOOS == "windows" || os.Geteuid() == 0 {
		t.Skip("needs POSIX permissions as a non-root user")
	}
	root := writeTree(t, map[string]string{"a.go": "package p\n"})
	if err := os.Chmod(filepath.Join(root, "a.go"), 0); err != nil {
		t.Fatal(err)
	}
	if _, err := AnalyzeTree(root); err == nil {
		t.Fatal("unreadable file not reported")
	}
}

func TestTreeMissingRoot(t *testing.T) {
	if _, err := AnalyzeTree(filepath.Join(t.TempDir(), "missing")); err == nil {
		t.Fatal("missing root accepted")
	}
}
