package render_test

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/michael-duren/go-skills/internal/config"
	"github.com/michael-duren/go-skills/internal/render"
	"github.com/michael-duren/go-skills/internal/testproject"
)

const sqlcLauncher = "github.com/sqlc-dev/sqlc/cmd/sqlc@v1.31.1"

func TestSQLCRegenerationIsStable(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the pinned sqlc")
	}
	for _, backend := range []string{"sqlite", "postgres"} {
		t.Run(backend, func(t *testing.T) {
			c := testproject.Config()
			c.Features.Database, c.Features.Access = backend, "sqlc"
			files, err := render.Files(c, "new")
			if err != nil {
				t.Fatal(err)
			}
			root := testproject.Write(t, files)
			dir := filepath.Join(root, "internal", "store", "queries")
			before := readDir(t, dir)
			if before["db.go"] == nil || before["models.go"] == nil || before["queries.sql.go"] == nil {
				t.Fatalf("bundled query files = %v", slices.Collect(mapsKeys(before)))
			}
			testproject.Go(t, root, "run", sqlcLauncher, "generate")
			after := readDir(t, dir)
			if len(after) != len(before) {
				t.Fatalf("regeneration changed the file set: %v", slices.Collect(mapsKeys(after)))
			}
			for name, data := range before {
				if !bytes.Equal(data, after[name]) {
					t.Fatalf("sqlc output drifted in %s", name)
				}
			}
		})
	}
}

func readDir(t *testing.T, dir string) map[string][]byte {
	t.Helper()
	entries, err := os.ReadDir(dir)
	if err != nil {
		t.Fatal(err)
	}
	out := map[string][]byte{}
	for _, e := range entries {
		data, err := os.ReadFile(filepath.Join(dir, e.Name()))
		if err != nil {
			t.Fatal(err)
		}
		out[e.Name()] = data
	}
	return out
}

func mapsKeys(m map[string][]byte) func(func(string) bool) {
	return func(yield func(string) bool) {
		for k := range m {
			if !yield(k) {
				return
			}
		}
	}
}

func TestSQLCGeneratedProjects(t *testing.T) {
	if testing.Short() {
		t.Skip("builds generated projects")
	}
	t.Run("sqlite http", func(t *testing.T) {
		buildAndTest(t, features(func(f *config.Features) { f.Database, f.Access, f.HTTP = "sqlite", "sqlc", "nethttp" }),
			append([]string{"TestHealth", "TestQueriesRoundTrip", "TestQueriesWithTx", "TestQueriesFailure"}, sqliteTests...)...)
	})
	t.Run("postgres cli", func(t *testing.T) {
		buildAndTest(t, features(func(f *config.Features) { f.Database, f.Access, f.CLI = "postgres", "sqlc", "cobra" }),
			append([]string{"TestStatus", "TestQueriesGet", "TestQueriesPut", "TestQueriesWithTx", "TestQueriesFailure"}, postgresTests...)...)
	})
}

func TestSQLCFilesAndCommands(t *testing.T) {
	c := testproject.Config()
	c.Features.Database, c.Features.Access = "postgres", "sqlc"
	files, err := render.Files(c, "new")
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{"sqlc.yaml", "sql/queries.sql", "sql/schema.sql", "internal/store/queries/db.go"} {
		testproject.File(t, files, path)
	}
	facade := string(testproject.File(t, files, "internal/store/store.go"))
	if !strings.Contains(facade, "queries.New(db)") || strings.Contains(facade, "Code generated") {
		t.Fatalf("facade:\n%s", facade)
	}
	if !strings.HasPrefix(string(testproject.File(t, files, "internal/store/queries/queries.sql.go")), "// Code generated by sqlc. DO NOT EDIT.") {
		t.Fatal("bundled query code is not sqlc output")
	}
	normalized, err := render.Normalize(c, "new")
	if err != nil {
		t.Fatal(err)
	}
	i := slices.IndexFunc(normalized.Commands, func(cmd config.Command) bool { return cmd.Name == "generate" })
	if i < 0 || !slices.Equal(normalized.Commands[i].Argv, []string{"go", "run", sqlcLauncher, "generate"}) {
		t.Fatalf("commands = %+v", normalized.Commands)
	}
	if normalized.Generator.Tools["sqlc"] != "v1.31.1" {
		t.Fatalf("tools = %v", normalized.Generator.Tools)
	}
	c.Features.Access = "sql"
	plain, err := render.Normalize(c, "new")
	if err != nil {
		t.Fatal(err)
	}
	if slices.ContainsFunc(plain.Commands, func(cmd config.Command) bool { return cmd.Name == "generate" }) {
		t.Fatal("generate advertised without sqlc")
	}
}
