package render_test

import (
	"bytes"
	"os"
	"path/filepath"
	"slices"
	"strings"
	"testing"

	"github.com/michael-duren/go-skills/internal/config"
	"github.com/michael-duren/go-skills/internal/render"
	"github.com/michael-duren/go-skills/internal/testproject"
)

const templLauncher = "github.com/a-h/templ/cmd/templ@v0.3.1020"

func webConfig(router, e2e string) config.Config {
	c := testproject.Config()
	c.Features.HTTP, c.Features.Web, c.Features.E2E = router, "htmx", e2e
	return c
}

func TestGeneratedWebFiles(t *testing.T) {
	files, err := render.Files(webConfig("chi", "playwright"), "new")
	if err != nil {
		t.Fatal(err)
	}
	for _, path := range []string{
		"internal/web/views.templ", "internal/web/web.go", "internal/web/web_test.go",
		"internal/web/static/htmx.min.js", "internal/web/static/alpine.min.js", "internal/web/static/THIRD_PARTY_LICENSES.md",
		"e2e/ui_test.go",
	} {
		testproject.File(t, files, path)
	}
	views := testproject.File(t, files, "internal/web/views_templ.go")
	if !bytes.HasPrefix(views, []byte("// Code generated by templ - DO NOT EDIT.")) {
		t.Fatal("bundled views are not templ output")
	}
	if !bytes.Contains(testproject.File(t, files, "internal/web/static/alpine.min.js"), []byte("{{")) {
		t.Fatal("Alpine bundle was altered by template rendering")
	}
	if !strings.HasPrefix(string(testproject.File(t, files, "e2e/ui_test.go")), "//go:build e2e") {
		t.Fatal("browser tests are not behind the e2e build tag")
	}
	routes := string(testproject.File(t, files, "internal/httpserver/routes.go"))
	if !strings.Contains(routes, `"example.com/demo/internal/web"`) {
		t.Fatalf("router does not mount the web UI:\n%s", routes)
	}
	normalized, err := render.Normalize(webConfig("chi", "playwright"), "new")
	if err != nil {
		t.Fatal(err)
	}
	names := commandNames(normalized.Commands)
	for _, want := range []string{"generate-templ", "setup-e2e", "test-e2e"} {
		if !slices.Contains(names, want) {
			t.Fatalf("commands = %v", names)
		}
	}
	agents := string(testproject.File(t, files, "AGENTS.md"))
	for _, want := range []string{"htmx", "Alpine.js", "templ", "Playwright", "`internal/web`", "`e2e`", "-tags e2e"} {
		if !strings.Contains(agents, want) {
			t.Errorf("guidance missing %q", want)
		}
	}
	plain, err := render.Files(webConfig("nethttp", "none"), "new")
	if err != nil {
		t.Fatal(err)
	}
	if _, ok := find(plain, "e2e/ui_test.go"); ok {
		t.Fatal("browser tests generated without Playwright")
	}
	if strings.Contains(string(testproject.File(t, plain, "AGENTS.md")), "Playwright") {
		t.Fatal("guidance mentions Playwright when it is not selected")
	}
}

func TestExistingWebGuidanceMentionsOnlyAvailableCommands(t *testing.T) {
	c := webConfig("chi", "playwright")
	c.Project.Go = "1.22"
	files, err := render.Files(c, "existing")
	if err != nil {
		t.Fatal(err)
	}
	agents := string(testproject.File(t, files, "AGENTS.md"))
	for _, bad := range []string{"`e2e`", "setup-e2e", "test-e2e", "generate-templ"} {
		if strings.Contains(agents, bad) {
			t.Errorf("existing-mode guidance mentions undefined %s:\n%s", bad, agents)
		}
	}
}

func TestGeneratedWebSecurityAndHead(t *testing.T) {
	files, err := render.Files(webConfig("chi", "none"), "new")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(testproject.File(t, files, "internal/web/web_test.go")), "TestIncrementRejectsCrossOrigin") {
		t.Fatal("cross-origin protection is not tested")
	}
	if !strings.Contains(string(testproject.File(t, files, "internal/httpserver/server_test.go")), "http.MethodHead") {
		t.Fatal("HEAD on static assets is not tested")
	}
}

func TestGeneratedWeb(t *testing.T) {
	if testing.Short() {
		t.Skip("builds generated projects")
	}
	webTests := []string{"TestPageEscapesTitle", "TestPageLoadsAssets", "TestIncrement", "TestConcurrentIncrements",
		"TestStaticAssets", "TestRenderFailure", "TestIncrementRejectsCrossOrigin", "TestWebRoutes", "TestHealth"}
	for _, tt := range []struct {
		name string
		f    config.Features
	}{
		{"nethttp", features(func(f *config.Features) { f.HTTP, f.Web = "nethttp", "htmx" })},
		{"chi playwright sqlite", features(func(f *config.Features) {
			f.HTTP, f.Web, f.E2E, f.Database, f.Access, f.CLI = "chi", "htmx", "playwright", "sqlite", "sql", "flag"
		})},
	} {
		t.Run(tt.name, func(t *testing.T) {
			c := testproject.Config()
			c.Features = tt.f
			files, err := render.Files(c, "new")
			if err != nil {
				t.Fatal(err)
			}
			root := testproject.Write(t, files)
			testproject.Go(t, root, "mod", "tidy")
			testproject.Go(t, root, "vet", "-tags", "e2e", "./...")
			out := testproject.Go(t, root, "test", "-count=1", "-race", "-v", "./...")
			for _, name := range webTests {
				if !strings.Contains(out, "--- PASS: "+name) {
					t.Errorf("generated test %s did not pass:\n%s", name, out)
				}
			}
		})
	}
}

func TestTemplRegenerationIsStable(t *testing.T) {
	if testing.Short() {
		t.Skip("runs the pinned templ")
	}
	files, err := render.Files(webConfig("nethttp", "none"), "new")
	if err != nil {
		t.Fatal(err)
	}
	root := testproject.Write(t, files)
	before := testproject.File(t, files, "internal/web/views_templ.go")
	testproject.Go(t, root, "run", templLauncher, "generate")
	after, err := os.ReadFile(filepath.Join(root, "internal", "web", "views_templ.go"))
	if err != nil {
		t.Fatal(err)
	}
	if !bytes.Equal(before, after) {
		t.Fatal("templ output drifted")
	}
}
